version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8
  sonarcloud: sonarsource/sonarcloud@2.0.0

executors: # Define an executor
  br-executor:
    docker:
      - image: cimg/node:18.17.0-browsers

jobs:

  build:
    working_directory: ~/br-angular-components-library
    executor: br-executor
    steps:
      - checkout
      - run: yarn install
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - run: yarn run build
      - save_cache:
          key: br-angular-components-library-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: yarn run test

  sonarcloud_scan:
    working_directory: ~/br-angular-components-library
    executor: br-executor
    steps:
      - checkout
      - sonarcloud/scan

workflows:
  build_and_test:
    jobs:
     - build
     - sonarcloud_scan:
        requires:
          - build
