version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.3
jobs:
  build:
    working_directory: ~/br-angular-components-library
    docker:
      - image: cimg/node:16.13.1-browsers
    steps:
      - checkout
      - run: yarn install
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - run: yarn run build
      - save_cache:
          key: br-angular-components-library-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: yarn run test
